version: "3.3"

services:
 
  spark:
    image: bde2020/spark-master:2.3.1-hadoop2.8
    hostname: 'spark'
    #ports: [ "18080:8080", "17077:7077" ]
    env_file: 'env.sh'
    environment:
      - "SPARK_MASTER_OPTS=-Dspark.master.rest.enabled=true"
    networks: ['hadoop-net']
    deploy:
      endpoint_mode: 'vip'
      placement:
        constraints: [ 'node.hostname == node-1.localdomain' ]

 
  worker:
    image: bde2020/spark-worker:2.3.1-hadoop2.8
    #hostname: 'worker1'
    env_file: 'env.sh'
    environment:
      - "SPARK_MASTER=spark://spark:7077"
    networks: ['hadoop-net'] 
    deploy:
      replicas: 4
      endpoint_mode: 'dnsrr'


networks:
  hadoop-net:
    external:
      name: 'hadoop-net'

