version: "3.3"

services:

  zeppelin:
    image: bde2020/zeppelin:0.8.0-hadoop-2.8.0-spark-2.3.1
    ports: 
      #- '18080:8080'
      - '18443:8443'
    hostname: zeppelin
    volumes:
      - ./shiro.ini:/opt/zeppelin/conf/shiro.ini
      - ./zeppelin-site.xml:/opt/zeppelin/conf/zeppelin-site.xml
      - ./keystore:/opt/zeppelin/conf/keystore
      - ./notebook:/opt/zeppelin/notebook
      #- ./examples:/opt/sansa-examples
    environment:
      - "CORE_CONF_fs_defaultFS=hdfs://namenode:8020"
      - "SPARK_MASTER=spark://spark:7077"
      - "MASTER=spark://spark:7077"
      #- "SPARK_SUBMIT_OPTIONS=--jars /opt/sansa-examples/jars/sansa-examples-spark.jar --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.kryo.registrator=org.datasyslab.geospark.serde.GeoSparkKryoRegistrator --conf spark.kryo.registrator=net.sansa_stack.owl.spark.dataset.UnmodifiableCollectionKryoRegistrator"
    networks: [ 'hadoop-net' ]
    deploy:
      endpoint_mode: 'vip'
      placement:
        constraints: [ 'node.hostname == node-1.localdomain' ]


networks:
  hadoop-net:
    external:
      name: 'hadoop-net'
